---
title: "Publications"
page-layout: full
---

<style>
  .citation {
    display: none;
  }
  .show-citation {
    display: block;
  }
</style>

<script>
  function toggleCitation(id) {
    var citationDiv = document.getElementById("citation-" + id);
    citationDiv.classList.toggle("show-citation");
  }
</script>

\

**ScripTONES: Sentiment-Conditioned Music Generation for Movie Scripts** \
_NeurIPS 2023 - Machine Learning for Audio Workshop, AIML Systems 2023 - Generative AI Workshop_ \
Vishruth Veerendranath, **Vibha Masti**, Utkarsh Gupta, Hrishit Chaudhuri, Gowri Srinivasa \
<a href="https://mlforaudioworkshop.com/ScripTONES.pdf" type="button" class="btn btn-outline-primary btn-sm">paper</a>
<a href="posters/ScripTONES.pdf" type="button" class="btn btn-outline-primary btn-sm">poster</a>
<a href="https://torpid-okra-923.notion.site/ScripTONES-Sentiment-Conditioned-Music-Generation-for-Movie-Scripts-fb7038d68112435ea120af2bb7cc64b0" type="button" class="btn btn-outline-primary btn-sm">website</a>


**C3PO: A Lightweight Copying Mechanism for Translating Pseudocode to Code** \
_AACL-IJCNLP 2022 - Student Research Workshop_ \
Vishruth Veerendranath, **Vibha Masti**, Prajwal Anagani, Mamatha HR  \
<a href="https://aclanthology.org/2022.aacl-srw.7" type="button" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://github.com/Pseudocode-to-Code/C3PO" type="button" class="btn btn-outline-primary btn-sm">code</a>
<button onclick="toggleCitation('c3po')" class="btn btn-outline-primary btn-sm">bib</button>

<div id="citation-c3po" class="citation">
  ```bib
  @inproceedings{veerendranath-etal-2022-c3po,
    title = "{C3PO}: {A} Lightweight Copying Mechanism for Translating Pseudocode to Code",
    author = "Veerendranath, Vishruth and Masti, Vibha and Anagani, Prajwal and Hr, Mamatha",
    booktitle = "Proceedings of the 2nd Conference of the Asia-Pacific Chapter of the Association for Computational Linguistics and the 12th International Joint Conference on Natural Language Processing: Student Research Workshop",
    month = nov,
    year = "2022",
    address = "Online",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/2022.aacl-srw.7",
    pages = "47--53"
  }
  ```
</div>


<!-- Add a bibtex button that opens a code block -->



**GraphCoReg: Co-Training for Regression on Temporal Graphs** \
_ECML-PKDD 2022 - International Workshop on Mining and Learning with Graphs_ \
Harshith Mohan Kumar, Vishruth Veerendranath, **Vibha Masti**, Divya Shekar, Bhaskarjyoti Das \
<span style="color: #E8590B"> **Student Best Paper Award** </span> :trophy: \
<a href="https://openreview.net/forum?id=JExuzizhS-p" type="button" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://github.com/Deep-Co-Training/GraphCoReg" type="button" class="btn btn-outline-primary btn-sm">code</a>
<button onclick="toggleCitation('graph')" class="btn btn-outline-primary btn-sm">bib</button>

<div id="citation-graph" class="citation">
  ```bib
  @inproceedings{
    kumar2022graphcoreg,
    title={GraphCoReg: Co-Training for Regression on Temporal Graphs},
    author={Harshith Mohan Kumar and Vishruth Veerendranath and Vibha Masti and Divya Shekar and Bhaskarjyoti Das},
    booktitle={18th International Workshop on Mining and Learning with Graphs},
    year={2022},
    url={https://openreview.net/forum?id=JExuzizhS-p}
  }
  ```
</div>

**Multivariate Covid-19 Forecasting with Vaccinations as a factor: the case of India and USA** \
_ICML 2022 - 1st Workshop on Healthcare AI and COVID-19, IEEE Region 10 Symposium (TENSYMP) 2022_ \
**Vibha Masti\***, Vishruth Veerendranath\*, Harshith Mohan Kumar\* \
<p><small>\*equal contribution </small></p>
<a href="https://ieeexplore.ieee.org/document/9864476" type="button" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://github.com/Data-Analytics-Project-2021/covid19-prediction" type="button" class="btn btn-outline-primary btn-sm">code</a>
<button onclick="toggleCitation('covid')" class="btn btn-outline-primary btn-sm">bib</button>

<div id="citation-covid" class="citation">
  ```bib
  @inproceedings{9864476,
    author={Masti, Vibha and Veerendranath, Vishruth and Kumar, Harshith Mohan},
    booktitle={2022 IEEE Region 10 Symposium (TENSYMP)}, 
    title={Multivariate Covid-19 Forecasting with Vaccinations as a factor: the case of India and USA}, 
    year={2022},
    volume={},
    number={},
    pages={1-6},
    doi={10.1109/TENSYMP54529.2022.9864476}}
  ```
</div>

**A Comparative Study of Algorithms for Intelligent Traffic Signal Control** \
Hrishit Chaudhuri, **Vibha Masti**, Vishruth Veerendranath, S Natarajan \
<a href="https://arxiv.org/abs/2109.00937" type="button" class="btn btn-outline-primary btn-sm">paper</a>
<a href="https://github.com/intelligent-traffic-signal/mini-proj-traffic" type="button" class="btn btn-outline-primary btn-sm">code</a>
<button onclick="toggleCitation('traffic')" class="btn btn-outline-primary btn-sm">bib</button>
<div id="citation-traffic" class="citation">
  ```bib
  @incollection{chaudhuri2022comparative,
    title={A comparative study of algorithms for intelligent traffic signal control},
    author={Chaudhuri, Hrishit and Masti, Vibha and Veerendranath, Vishruth and Natarajan, S},
    booktitle={Machine Learning and Autonomous Systems: Proceedings of ICMLAS 2021},
    pages={271--287},
    year={2022},
    publisher={Springer}
  }
  ```
</div>